env:
  browser: true
  es2021: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  comma-dangle: [error, always-multiline]
  max-len: [error, 120]
  no-useless-constructor: 'off'
  object-curly-spacing: [error, 'never']
  space-before-function-paren: 'off'
